@startuml Architettura_logica

' usare MVC (Model-View-Controller):
' - Model: database
' - View: interfaccia grafica
' - Controller: Software vero e proprio

' Il Controllore sarà diviso in "categorie di classi"
' usando architettura a strati modulare.

' Modello, View e Controllore devono poter comunicare tra loro.

' Da fare una relazione alla fine del progetto


' Tenere a mente Client-Server
' Il database può essere "finto" (obv)
' DISEGNINO A BLOCKLY CHE A NOI CI PIACCIONO I DISEGNINI
'
' Prossimi passaggi:
' 1) Definire i requisiti NON funzionali (non direttamente legati alle
'    funzionalità del sistema) e definire come misurarli:
'    ad esempio misure di velocità, performance ecc ecc...
'
' 2) Definire i requisiti funzionali come le user story
'    (ricorda la sintassi Who-What-Why) e gli Acceptance Criteria
'
'

' View, cosa mettere dentro:
' - Visualizzatore di scenari
' - Menu' di eventi
' - Visualizzatore di eventi
' - Visualizzatore di inventario/statistiche
' - Menu' principale
' - Lobby d'attesa + scelta personaggio
' - Visualizzatore di mappa livello
' - Menu' opzioni
'

' - Per gli eventi, possibile implementazione tramite Strategy

frame "Interfaccia" {
  ' Permettono visualizzazione di scelta di opzioni (Tramite Controllore)
  frame "MENU" {
    ' Scelta di Inizio, Opzioni, Crediti    
    note "Scelta di Inizio, Opzioni, Crediti" as Peppe
    frame "Menu' principale" {

    }
    "Menu' principale" -> Peppe
    ' Scelta delle Impostazioni/Opzioni
    frame "Menu' di opzioni" {

    }
    ' Scelta degli eventi/opzioni in uno scenario
    frame "Menu' Scenario" {

    }
    ' Scelta delle operazioni da fare in un Evento
    frame "Menu' dell'Evento" {

    }
    ' Scelta della Classe
    frame "Menu' Scelta Personaggio" {

    }
  }

    ' Permette la visualizzazione senza scelte (Tramite Controllore)
  frame "VISUALIZZATORI" {
    ' Mostra le info di un evento in particolare
    ' (Quello scelto dal menu')
    frame "Visualizzatore Info Evento" {

    }
    ' Mostra le stats di ogni giocatore
    frame "Visualizzatore di inventario/statistiche" {

    }
    ' Mostra la lista degli scenari (no MENU')
    frame "Visualizzatore di mappa livello" {

    }
    
    ' "Visualizzatore Info Evento" <-down- "Menu' Scenario"
  }

  ' "Menu' di opzioni" <-down- "Menu' principale"
  ' "Menu' Scelta Personaggio" <-down- "Menu' principale"
  ' "Menu' di eventi" <-down- "Visualizzatore di scenari"
  ' "Visualizzatore di mappa livello" <-down- "Menu' Scelta Personaggio"
  ' "Visualizzatore di eventi" <-down- "Menu' di eventi"
  
  "VISUALIZZATORI" <-[hidden]down- "MENU"
}

' - Statici
' - Dati relativi agli eventi: nome, desc, tipologia, (potenziale) immagine
' - Dati relativi all'equipaggiamento
' - Dati relativi ai potenziamenti
' - Dati relativi ai classi, nemici
' - Dati opzioni

' - Dinamici
' - History eventi (passati e non)
' - Scenari (futuri)
' - Boss
' - Livelli
' - Giocatori (Runtime)
' - Eventuali dati di output (per possibile log della partita)

frame "Modello" {
  ' Dati che funzionano come 'Database'
  frame "DatiStatici" {
    frame "DatiEventi" {

    }
    frame "DatiEquip" {

    }
    frame "DatiPotenziamenti" {

    }
    frame "DatiClassi" {

    }
    frame "DatiNemici" {

    }
    frame "DatiOpzioni" {

    }
  }

  ' Dati relativi alla sessione di gioco corrente
  frame "DatiDinamici" {
    frame "DatiHistory" {

    }
    note bottom of "DatiHistory": "Progressione fino al tempo attuale"

    frame "DatiGiocatori" {

    }
    note bottom of "DatiGiocatori": "Dati Personaggi Runtime"
    
    frame "DatiLivelli" {
        frame "DatiBoss" {

      }
      frame "DatiScenari" {
      
      }
    }
  }
  "DatiGiocatori" -up-> "DatiClassi" : <<uses>>
  "DatiGiocatori" -up-> "DatiPotenziamenti" : <<uses>>
  "DatiGiocatori" -up-> "DatiEquip" : <<uses>>

  "DatiLivelli" -up-> "DatiNemici" : <<uses>>
  "DatiLivelli" -up-> "DatiEventi" : <<uses>>

  "DatiHistory" -right-> "DatiLivelli" : <<uses>>
  "DatiHistory" -left-> "DatiGiocatori" : <<uses>>

  "DatiBoss" -[hidden]down-> "DatiScenari"
  "DatiStatici" <-[hidden]down- "DatiDinamici"
}

' - ControllerGameLogic
' - ControllerMiddleware
' - ControllerUserInput
' - ControllerViewOutput

frame "Controllore" {
  
  frame "ControllerGameLogic" {

  }
  note top of "ControllerGameLogic": "Loop di gioco"
  
  frame "ControllerMiddleware" {

  }
  note top of "ControllerMiddleware": "collegamento con il Model - sfrutta ControllerIO"
  
  frame "ControllerUserInput" {

  }
  note top of "ControllerUserInput": "Input con l'utente"
  
  frame "ControllerViewOutput" {

  }
  note top of "ControllerViewOutput": "Output sullo schermo"

  "ControllerGameLogic" -up-> "ControllerMiddleware" : <<uses>>
  "ControllerGameLogic" -up-> "ControllerUserInput" : <<uses>>
  "ControllerGameLogic" -up-> "ControllerViewOutput" : <<uses>>

}

actor Utente

Utente -up-> "ControllerUserInput"
"ControllerViewOutput" -left-> "Interfaccia" : <<uses>>
"ControllerMiddleware" -up-> "Modello" : <<uses>>
"Controllore" <--[hidden]up- "Interfaccia"
@enduml